### ISSUE TITLE
Unregistered user avatar is stretched (LUNA 1.4 - 2.0)

### ISSUE THREAD

**Issue by Scrumplex** [GetLuna/Luna#1587] opened 2016-04-12 14:21 UTC
Hello there,
the placeholder avatar in the front page is stretched if you are not logged in.
I am using Fifteen as the theme and I have _Show the first run panel to guests with login field and registration button._ under **Features** enabled. The stretching occurrs because of the _HTML4_ width and height properties on _img_ tags.
[Screenshot](http://i.imgur.com/KCFD1c3.png)
[Live preview](https://forum.sprum.ml/)

**Comment by Studio384** [comment] 2016-04-12 15:33
Thank you for reporting.

**Comment by Studio384** [comment] 2016-04-12 16:13
I'm sorry, but I'm unable to reproduce this. Luna does not apply a ```width``` nor a ```height``` property to the img-tag.

**Comment by Studio384** [comment] 2016-04-12 16:20
This is the HTML code that is generated by Luna for the avatar:

```html
<img class="img-responsive avatar" alt="" src="http://localhost/luna/img/avatars/placeholder.png">
```

**Comment by Scrumplex** [comment] 2016-04-12 16:27
I already deleted luna without the avatars and config (and also i kept mysql data) and reinstalled it completely (except mysql and so on) and it was there so I don't know why that happens.

**Comment by Studio384** [comment] 2016-04-12 16:35
I've pushed a fix to the CSS that fixes it for your site, but as far as I'm aware, this doesn't happen on clean Luna installations. Is your website influenced by something?

**Closed** 2016-04-12 16:35 UTC
Labels: behavior, bug, interface, theme
